version: '3.8'

services:
  jekyll:
    build: .
    image: hack4life-jekyll:latest
    container_name: hack4life-jekyll
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/vendor
      - /app/.bundle
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --host 0.0.0.0 --port 4000 --livereload --force_polling
