title: Hack4Life
description: A collection of hardware hacks and reverse engineering projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cat101.github.io/hack4life" # the base hostname & protocol for your site, e.g. http://example.com

# Repository information for GitHub metadata
repository: cat101/hack4life

# Theme settings
theme: "just-the-docs"

# Enable or disable the site search
search_enabled: true

# Set the search token separator
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  rel_url: true

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "//github.com/cat101/hack4life"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Custom CSS
sass:
  sass_dir: _sass
  style: compressed

# Navigation structure
nav_sort: case_insensitive

# Enable back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Google Analytics Tracking (optional)
# ga_tracking: UA-NNNNNNNN-N
# ga_tracking_anonymize_ip: true

# Callouts
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
  highlight:
    title: Important
    color: yellow

# Footer content
footer_content: "Copyright &copy; 2009-2025 Matias Cuenca. Documentation of various hardware hacking projects."

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/cat101/hack4life"
gh_edit_branch: "master"
gh_edit_view_mode: "edit"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - update_html_titles.py
  - current/
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - "**/Exploration/**"
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - archive/
